// Avatar customiser modal — preset picker for the sprite-sheet era.
// (Earlier mix-and-match customiser is gone; presets are full looks
// generated by Retro Diffusion.)
(() => {
  const den       = window.den;
  const modal     = document.getElementById('customiser');
  const closeBtn  = document.getElementById('custClose');
  const saveBtn   = document.getElementById('custSave');
  const profile   = document.getElementById('profile');
  const content   = document.getElementById('custContent');
  const previewC  = document.getElementById('avatarPreview');
  const previewX  = previewC.getContext('2d');
  previewX.imageSmoothingEnabled = false;
  // Match the preview canvas to the sprite frame size
  previewC.width  = den.FRAME_W;
  previewC.height = den.FRAME_H;

  // Hide the now-unused tab bar
  const tabsEl = document.getElementById('custTabs');
  if (tabsEl) tabsEl.style.display = 'none';

  let draftPreset = den.me.cfg.preset;
  const spriteCache = {}; // id -> Image

  function loadSprite(id) {
    if (spriteCache[id]) return spriteCache[id];
    const img = new Image();
    img.src = `sprites/${id}.png?v=${den.SPRITE_VERSION ?? 1}`;
    spriteCache[id] = img;
    return img;
  }

  function renderPreview() {
    const img = loadSprite(draftPreset);
    const draw = () => {
      previewX.clearRect(0, 0, previewC.width, previewC.height);
      previewX.drawImage(img, 0, 0, den.FRAME_W, den.FRAME_H, 0, 0, previewC.width, previewC.height);
    };
    if (img.complete) draw();
    else img.onload = draw;
  }

  function renderGrid() {
    content.innerHTML = '';

    const label = document.createElement('div');
    label.className = 'cust-section-label';
    label.textContent = 'Look';
    content.appendChild(label);

    const row = document.createElement('div');
    row.className = 'styles-row';
    row.style.gap = '12px';
    content.appendChild(row);

    for (const p of den.presets) {
      row.appendChild(makeChip(p));
    }
  }

  function makeChip(preset) {
    const active = preset.id === draftPreset;
    const div = document.createElement('div');
    div.className = 'style-chip' + (active ? ' active' : '');

    const c = document.createElement('canvas');
    c.width = den.FRAME_W;
    c.height = den.FRAME_H;
    const cx = c.getContext('2d');
    cx.imageSmoothingEnabled = false;
    const img = loadSprite(preset.id);
    const blit = () => cx.drawImage(img, 0, 0, den.FRAME_W, den.FRAME_H, 0, 0, c.width, c.height);
    if (img.complete) blit(); else img.onload = blit;

    const lbl = document.createElement('div');
    lbl.className = 'lbl';
    lbl.textContent = preset.name;

    div.appendChild(c);
    div.appendChild(lbl);
    div.onclick = () => {
      draftPreset = preset.id;
      renderGrid();
      renderPreview();
    };
    return div;
  }

  function open() {
    draftPreset = den.me.cfg.preset;
    renderGrid();
    renderPreview();
    modal.classList.add('open');
  }
  function close() { modal.classList.remove('open'); }
  function save() {
    den.setPreset(den.me, draftPreset);
    close();
    // TODO: PUT /users/me/avatar with { preset: draftPreset }
  }

  profile.addEventListener('click', open);
  closeBtn.addEventListener('click', close);
  saveBtn.addEventListener('click', save);
})();
