// Auto-generated: every historical version of every piece, exposed in the editor
// under the "Archive" category so you can browse variants side-by-side.
const ARCHIVE_CATALOG = [
  { id: 'bed_blue_v1', name: 'Blue bed v1', category: 'archive', scale: 1.5, footprint: [2, 1] },
  { id: 'bed_blue_v2', name: 'Blue bed v2', category: 'archive', scale: 1.5, footprint: [2, 1] },
  { id: 'bed_blue_v3', name: 'Blue bed v3', category: 'archive', scale: 1.5, footprint: [2, 1] },
  { id: 'bed_blue_v4', name: 'Blue bed v4', category: 'archive', scale: 1.5, footprint: [2, 1] },
  { id: 'bed_blue_v5', name: 'Blue bed v5', category: 'archive', scale: 1.5, footprint: [2, 1] },
  { id: 'bed_blue_v6', name: 'Blue bed v6', category: 'archive', scale: 1.5, footprint: [2, 1] },
  { id: 'bed_blue_v7', name: 'Blue bed v7', category: 'archive', scale: 1.5, footprint: [2, 1] },
  { id: 'bed_blue_v8', name: 'Blue bed v8', category: 'archive', scale: 1.5, footprint: [2, 1] },
  { id: 'bed_blue_v9', name: 'Blue bed v9', category: 'archive', scale: 1.5, footprint: [2, 1] },
  { id: 'bookshelf_v1', name: 'Bookshelf v1', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'bookshelf_v2', name: 'Bookshelf v2', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'bookshelf_v3', name: 'Bookshelf v3', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'bookshelf_v4', name: 'Bookshelf v4', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'bookshelf_v5', name: 'Bookshelf v5', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'chair_wood_v1', name: 'Wooden chair v1', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'chair_wood_v2', name: 'Wooden chair v2', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'chair_wood_v3', name: 'Wooden chair v3', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'chair_wood_v4', name: 'Wooden chair v4', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'chair_wood_v5', name: 'Wooden chair v5', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'chair_wood_v6', name: 'Wooden chair v6', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'computer_v1', name: 'Computer v1', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'computer_v2', name: 'Computer v2', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'computer_v3', name: 'Computer v3', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'computer_v4', name: 'Computer v4', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'computer_v5', name: 'Computer v5', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'computer_v6', name: 'Computer v6', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'desk_wood_v1', name: 'Wooden desk v1', category: 'archive', scale: 1.5, footprint: [2, 1] },
  { id: 'desk_wood_v2', name: 'Wooden desk v2', category: 'archive', scale: 1.5, footprint: [2, 1] },
  { id: 'desk_wood_v3', name: 'Wooden desk v3', category: 'archive', scale: 1.5, footprint: [2, 1] },
  { id: 'desk_wood_v4', name: 'Wooden desk v4', category: 'archive', scale: 1.5, footprint: [2, 1] },
  { id: 'desk_wood_v5', name: 'Wooden desk v5', category: 'archive', scale: 1.5, footprint: [2, 1] },
  { id: 'doorway_v1', name: 'Doorway v1', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'doorway_v2', name: 'Doorway v2', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'doorway_v3', name: 'Doorway v3', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'doorway_v4', name: 'Doorway v4', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'doorway_v5', name: 'Doorway v5', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'fish_tank_v1', name: 'Fish tank v1', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'fish_tank_v2', name: 'Fish tank v2', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'fish_tank_v3', name: 'Fish tank v3', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'fish_tank_v4', name: 'Fish tank v4', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'fish_tank_v5', name: 'Fish tank v5', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'fridge_v1', name: 'Fridge v1', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'fridge_v2', name: 'Fridge v2', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'fridge_v3', name: 'Fridge v3', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'fridge_v4', name: 'Fridge v4', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'fridge_v5', name: 'Fridge v5', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'fridge_v6', name: 'Fridge v6', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'fridge_v7', name: 'Fridge v7', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'fridge_v8', name: 'Fridge v8', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'lamp_floor_v1', name: 'Floor lamp v1', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'lamp_floor_v2', name: 'Floor lamp v2', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'lamp_floor_v3', name: 'Floor lamp v3', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'lamp_floor_v4', name: 'Floor lamp v4', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'lamp_floor_v5', name: 'Floor lamp v5', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'painting_v1', name: 'Painting v1', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'painting_v2', name: 'Painting v2', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'painting_v3', name: 'Painting v3', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'painting_v4', name: 'Painting v4', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'painting_v5', name: 'Painting v5', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'plant_tall_v1', name: 'Tall plant v1', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'plant_tall_v2', name: 'Tall plant v2', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'plant_tall_v3', name: 'Tall plant v3', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'plant_tall_v4', name: 'Tall plant v4', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'plant_tall_v5', name: 'Tall plant v5', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'plant_tall_v6', name: 'Tall plant v6', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'rug_persian_v1', name: 'Persian rug v1', category: 'archive', scale: 1.5, footprint: [2, 2], layer: 'floor' },
  { id: 'rug_persian_v2', name: 'Persian rug v2', category: 'archive', scale: 1.5, footprint: [2, 2], layer: 'floor' },
  { id: 'rug_persian_v3', name: 'Persian rug v3', category: 'archive', scale: 1.5, footprint: [2, 2], layer: 'floor' },
  { id: 'rug_persian_v4', name: 'Persian rug v4', category: 'archive', scale: 1.5, footprint: [2, 2], layer: 'floor' },
  { id: 'rug_persian_v5', name: 'Persian rug v5', category: 'archive', scale: 1.5, footprint: [2, 2], layer: 'floor' },
  { id: 'rug_persian_v6', name: 'Persian rug v6', category: 'archive', scale: 1.5, footprint: [2, 2], layer: 'floor' },
  { id: 'sofa_red_v1', name: 'Red sofa v1', category: 'archive', scale: 1.5, footprint: [2, 1] },
  { id: 'sofa_red_v2', name: 'Red sofa v2', category: 'archive', scale: 1.5, footprint: [2, 1] },
  { id: 'sofa_red_v3', name: 'Red sofa v3', category: 'archive', scale: 1.5, footprint: [2, 1] },
  { id: 'sofa_red_v4', name: 'Red sofa v4', category: 'archive', scale: 1.5, footprint: [2, 1] },
  { id: 'sofa_red_v5', name: 'Red sofa v5', category: 'archive', scale: 1.5, footprint: [2, 1] },
  { id: 'sofa_red_v6', name: 'Red sofa v6', category: 'archive', scale: 1.5, footprint: [2, 1] },
  { id: 'table_round_v1', name: 'Round table v1', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'table_round_v2', name: 'Round table v2', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'table_round_v3', name: 'Round table v3', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'table_round_v4', name: 'Round table v4', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'table_round_v5', name: 'Round table v5', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'table_round_v6', name: 'Round table v6', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'tv_crt_v1', name: 'CRT TV v1', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'tv_crt_v2', name: 'CRT TV v2', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'tv_crt_v3', name: 'CRT TV v3', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'tv_crt_v4', name: 'CRT TV v4', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'tv_crt_v5', name: 'CRT TV v5', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'tv_crt_v6', name: 'CRT TV v6', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'window_v1', name: 'Window v1', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'window_v2', name: 'Window v2', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'window_v3', name: 'Window v3', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'window_v4', name: 'Window v4', category: 'archive', scale: 1.5, footprint: [1, 1] },
  { id: 'window_v5', name: 'Window v5', category: 'archive', scale: 1.5, footprint: [1, 1] },
];
