import 'dart:ui' as ui;
import 'package:flutter/material.dart';
import '../../core/palette.dart';
import '../room/components/avatar_component.dart';
import 'wardrobe.dart';

/// Avatar customiser as a full-height bottom sheet.
///
/// With sprite sheets generated by Retro Diffusion, customisation is now
/// "pick a preset look" rather than mix-and-match parts. Live preview at
/// the top, grid of preset chips below.
class CustomiserSheet extends StatefulWidget {
  final AvatarConfig initial;
  final void Function(AvatarConfig) onSave;

  const CustomiserSheet({super.key, required this.initial, required this.onSave});

  @override
  State<CustomiserSheet> createState() => _CustomiserSheetState();
}

class _CustomiserSheetState extends State<CustomiserSheet> {
  late AvatarConfig _draft = widget.initial;

  @override
  Widget build(BuildContext context) {
    return Material(
      color: DenPalette.bg,
      child: SafeArea(
        child: Column(
          children: [
            _header(),
            _previewStage(),
            Expanded(child: _grid()),
          ],
        ),
      ),
    );
  }

  Widget _header() => Container(
        padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
        decoration: const BoxDecoration(
          border: Border(bottom: BorderSide(color: DenPalette.border)),
        ),
        child: Row(
          children: [
            GestureDetector(
              onTap: () => Navigator.of(context).pop(),
              child: Container(
                width: 36, height: 36,
                decoration: const BoxDecoration(
                  color: DenPalette.surfaceAlt,
                  shape: BoxShape.circle,
                ),
                child: const Icon(Icons.close_rounded, size: 18, color: DenPalette.text),
              ),
            ),
            const SizedBox(width: 12),
            const Text('My avatar',
                style: TextStyle(color: DenPalette.text, fontSize: 16, fontWeight: FontWeight.w600)),
            const Spacer(),
            GestureDetector(
              onTap: () {
                widget.onSave(_draft);
                Navigator.of(context).pop();
              },
              child: Container(
                padding: const EdgeInsets.symmetric(horizontal: 18, vertical: 8),
                decoration: BoxDecoration(
                  color: DenPalette.accent,
                  borderRadius: BorderRadius.circular(16),
                ),
                child: const Text('Save',
                    style: TextStyle(color: Colors.black, fontWeight: FontWeight.w700, fontSize: 13)),
              ),
            ),
          ],
        ),
      );

  Widget _previewStage() => Container(
        height: 240,
        decoration: const BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment.topCenter,
            end: Alignment.bottomCenter,
            colors: [Color(0xFF20324A), Color(0xFF18223A)],
          ),
        ),
        alignment: Alignment.center,
        child: SizedBox(
          width: 192, height: 192,
          child: SpritePreview(preset: _draft.preset),
        ),
      );

  Widget _grid() => SingleChildScrollView(
        padding: const EdgeInsets.fromLTRB(14, 16, 14, 32),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Text(
              'LOOK',
              style: TextStyle(
                color: DenPalette.textMuted,
                fontSize: 11,
                letterSpacing: 1.2,
                fontWeight: FontWeight.w600,
              ),
            ),
            const SizedBox(height: 10),
            Wrap(
              spacing: 12,
              runSpacing: 12,
              children: Wardrobe.presets.map(_chip).toList(),
            ),
          ],
        ),
      );

  Widget _chip(AvatarPreset p) {
    final active = p.id == _draft.preset;
    return GestureDetector(
      onTap: () => setState(() => _draft = _draft.copyWith(preset: p.id)),
      child: Container(
        padding: const EdgeInsets.all(6),
        decoration: BoxDecoration(
          color: DenPalette.surfaceAlt,
          borderRadius: BorderRadius.circular(10),
          border: Border.all(
            color: active ? DenPalette.accent : DenPalette.border,
            width: active ? 1.5 : 1,
          ),
        ),
        child: Column(
          children: [
            SizedBox(
              width: 56, height: 84,
              child: SpritePreview(preset: p.id),
            ),
            const SizedBox(height: 4),
            Text(
              p.name,
              style: const TextStyle(
                color: DenPalette.text, fontSize: 11, fontWeight: FontWeight.w500,
              ),
            ),
          ],
        ),
      ),
    );
  }
}

/// Shows the idle frame (col 0, row 0) of a sprite sheet at any scale,
/// pixelated. Used in the customiser preview stage and the chips.
class SpritePreview extends StatefulWidget {
  final String preset;
  const SpritePreview({super.key, required this.preset});

  @override
  State<SpritePreview> createState() => _SpritePreviewState();
}

class _SpritePreviewState extends State<SpritePreview> {
  ui.Image? _img;
  String? _loadedPreset;

  @override
  void initState() {
    super.initState();
    _load();
  }

  @override
  void didUpdateWidget(SpritePreview old) {
    super.didUpdateWidget(old);
    if (_loadedPreset != widget.preset) _load();
  }

  Future<void> _load() async {
    final img = await loadSpriteSheet(widget.preset);
    if (!mounted) return;
    setState(() {
      _img = img;
      _loadedPreset = widget.preset;
    });
  }

  @override
  Widget build(BuildContext context) {
    final img = _img;
    if (img == null) return const SizedBox.shrink();
    return LayoutBuilder(
      builder: (_, c) => CustomPaint(
        size: Size(c.maxWidth, c.maxHeight),
        painter: _FramePainter(img),
      ),
    );
  }
}

class _FramePainter extends CustomPainter {
  final ui.Image image;
  _FramePainter(this.image);

  @override
  void paint(Canvas canvas, Size size) {
    canvas.drawImageRect(
      image,
      // Idle frame is col 0, row 0 (south facing)
      Rect.fromLTWH(0, 0, AvatarComponent.frameW, AvatarComponent.frameH),
      Rect.fromLTWH(0, 0, size.width, size.height),
      Paint()..filterQuality = FilterQuality.none,
    );
  }

  @override
  bool shouldRepaint(covariant _FramePainter old) => old.image != image;
}
